services:
  - type: web
    name: demon-top-up-haiti
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: KOBARA_KEY
        sync: false
      - key: VISA_CHECKOUT_URL
        sync: false
